baseurl = "http://arvinsim.github.io/artem"
title = "Arthur's Ridiculous Text Expression Machine"
languageCode = "en-us"
theme = "hugo-theme-artem"

[author]
    name = "Arthur Vincent Simon"

[params]
    description = "A hobby blog"

[params.social]
    mail = "developarvin+artem@gmail.com"
    twitter = "http://twitter.com/developarvin"

[taxonomies]
    articleType = "articleTypes"
    discipline = "disciplines"
    tag = "tags" 
