baseurl = "http://arvinsim.github.io/artem"
title = "Arthur's Ridiculous Text Expression Machine"
languageCode = "en-us"
theme = "hugo-theme-artem"

[params]
    author = "Arthur Vincent Simon"
    description = "A hobby blog"

[params.social]
    mail = "developarvin+artem@gmail.com"
    twitter = "http://twitter.com/developarvin"

[taxonomies]
    articleType = "articleTypes"
    tag = "tags" 
